sudo: required
dist: trusty
language: node_js
node_js:
- '9'
install:
- npm install
- npm install codecov -g
script:
- npm run build
- npm run test
- npm run coverage
deploy:
  provider: npm
  email: npm@outrunlabs.com
  skip_cleanup: true
  api_key:
    secure: 2UjIClfIRi0SNDbRPx9eVOyFWyFQxuor1IAJZmZB3snuB1Ixfa9pBj/9G35HpJCQOx5Fa7gO2q4+ZZujQo0ohB0CR1XbtG761n14dAZn4MIrmQIfreLUAh8Lwejx29Oow20voHeGzpZdvATWObJHfvCy9ujhukCJsx5oRjwmiOVKqeFUoN5CJPPI6owgMdavhJZAI5toCtear5b7HrTL8wflVkDJyviEKauko7Ibeapa0B7LekWHVIm3G/Spc+512haYcib6nM8KMgAJO7zZL0cYby13xqO+HQEKfTccmcA1O4RtGR6NR5kN0vsqrz0XPv9MjltNJPsVj8nE+lmsiSYt7BGV+fg9TaTvBcUUvnUinNJuOHlKQMACeTrBrT0nicsMfGwKuqtdoPj1zxPw400liZYNrLpds0IT//2xIioRKeUf5Y1Qfb2XtHO1Nb4k2sM7AOtC3RqN+n3vgIdb5RrkhBzSKRqclFtGeIJua2UMVaNSs5F2fX6E4Gh0IMd7DonM1EuzVRfNzXgkzdCyGa8x1LtHmC5i76axhyKWpOAta5qCtRZmnHGDqjqcWObF9kJtenpQBulvMbb6edlXWByKGpJqQgSyfxdexXGDMplnQmjFfTN15vyMXMngw4kXF3lVB5kIpieSAJrsYblJSd9W2obw1gclD8Ev8wvJ1CE=
  on:
    repo: outrunlabs/outrun-content-pipeline
